apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-classic-wallaby
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "532560123509"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: innate-portal-317206
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: OrgNameRavi
    repository: GoogleSecretManager
  - key: staging
  - key: production
  ingress:
    domain: 34.69.114.99.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: ravi6337
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-classic-wallaby-0aaac4b505b5
  - name: reports
    url: gs://reports-tf-jx-classic-wallaby-0aaac4b505b5
  - name: repository
    url: gs://repository-tf-jx-classic-wallaby-0aaac4b505b5
  vault: {}
  webhook: lighthouse
